FROM node:lts-alpine

RUN mkdir -p /home/node/backend/node_modules && chown -R node:node /home/node/backend

WORKDIR /home/node/backend

COPY ./backend/package.json ./backend/yarn.* ./

## THE LIFE SAVER
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait

RUN chmod +x /wait

USER node

COPY --chown=node:node ./backend .

RUN rm -rf node_modules

RUN yarn

RUN yarn build

EXPOSE 5000

CMD /wait && yarn build:migration && yarn start
