version: '3'

services: 
  mapet-backend:
    build: 
      context: .
      dockerfile: dockerfile-backend
    container_name: mapet-backend
    ports: 
      - '5000:5000'
    depends_on: 
      - mapet-database
    networks: 
      - mapet-network
    environment:
      WAIT_HOSTS: mapet-database:3306

  mapet-database:
    image: mariadb
    container_name: mapet-database
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mapet
    volumes:
      - mapet-database-data:/var/lib/mysql
    networks: 
      - mapet-network      

volumes: 
  mapet-database-data:

networks:
  mapet-network:
    driver: bridge